# Generated by Django 4.0.4 on 2022-04-13 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=100)),
                ('price', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='New_order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('foods', models.ManyToManyField(to='shop.food')),
            ],
        ),
    ]
